[tool.black]
line-length = 88
target-version = ["py312"]
include = '\\.(py|pyi)$'

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = [
  "E501", # line-length handled by Black
  "B008", # FastAPI Depends in function signatures is idiomatic
]

[tool.ruff.lint.isort]
known-first-party = ["app", "tests"]
combine-as-imports = true
